First_name = input("First name; ")
Surname = input("Surname: ")
Age = int(input("Age: "))
Favourite_number = round(float(input("Favourite number: ")),2)
full_name = First_name.upper().title() + " " + Surname.upper().title()
age = int(Age * 12)
print(f"Welcome , {full_name}!")
print(f"Full name: {full_name}")
print(f" Age: {age}")
print(f"Favourite number: {Favourite_number}")
print(type(First_name), type(Surname), type(Age), type(Favourite_number))